import * as stylex from "@stylexjs/stylex";

const styles = stylex.create({
  fillColumn: { flexGrow: 1, minWidth: 0, minHeight: 0, display: "flex", flexDirection: "column" },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    paddingInline: 24,
    paddingBlock: 12,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--color-border-secondary)",
    flexShrink: 0,
  },
  headerGrow: { flexGrow: 1, minWidth: 0 },
  headerTitle: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  composerWrap: {
    flexShrink: 0,
    paddingInline: 24,
    paddingBlock: 16,
    maxWidth: 860,
    width: "100%",
    marginInline: "auto",
    boxSizing: "border-box",
  },
  composerDropZone: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  composerActions: {
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  hiddenFileInput: { display: "none" },
  stagedAttachments: {
    display: "flex",
    gap: 8,
    overflowX: "auto",
    paddingBlock: 2,
  },
  stagedAttachment: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
    padding: 6,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--color-border-secondary)",
    borderRadius: "var(--radius-md)",
    backgroundColor: "var(--color-background-surface)",
  },
  attachmentImage: {
    display: "block",
    width: 112,
    height: 84,
    maxWidth: "100%",
    objectFit: "cover",
    borderRadius: "var(--radius-md)",
  },
  attachmentFile: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 120,
    maxWidth: 260,
    color: "inherit",
    textDecoration: "none",
    overflow: "hidden",
  },
  messageContent: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    whiteSpace: "pre-wrap",
  },
  activityWrap: { paddingInline: 8 },
  approvalRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
    paddingInline: 8,
  },
});

export default styles;
